name: Deploy Model from W&B

on:
  repository_dispatch:
    types: [wandb-production-deploy] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal wandb numpy pillow fastapi tensorflow python-multipart

      - name: Configure Modal token
        run: modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Deploy to Modal
        run: modal deploy server.py